https

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,20 +1,36 @@
 #!/usr/bin/env bash
-# script must accept 2 arguments: domain and subdomain
-#Output:The subdomain is a [RECORD_TYPE] and points to [DESTINATION]
 
-get_dns_inf () {
-    get=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
-    echo "$2 $get" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
+# Function to display DNS record information
+display_dns_record() {
+    local record_type=$(echo "$1" | awk '{print $4}')
+    local destination=$(echo "$1" | awk '{print $5}')
+    echo "The subdomain $2 is a $record_type record and points to $destination"
 }
 
-if [ "$#" == 1 ]
-then
-  get_dns_inf "$1" "www"
-  get_dns_inf "$1" "lb-01"
-  get_dns_inf "$1" "web-01"
-  get_dns_inf "$1" "web-02"
-
-elif [ "$#" == 2 ]
-then
-  get_dns_inf "$1" "$2"
+# Check if domain argument is provided
+if [ -z "$1" ]; then
+    echo "Error: Domain name is required."
+    exit 1
 fi
+
+# Default subdomains to check if no subdomain argument is provided
+declare -a subdomains=("www" "lb-01" "web-01" "web-02")
+
+# If a subdomain argument is provided, check only that subdomain
+if [ -z "$2" ]; then
+    subdomains=("$2")
+fi
+
+# Loop through each subdomain and display its DNS record information
+for subdomain in "${subdomains[@]}"; do
+    # Query DNS record for the subdomain
+    record_info=$(dig +short "$subdomain.$1" A)
+    
+    # Check if the record_info variable is not empty
+    if [ -n "$record_info" ]; then
+        # Display the DNS record information
+        display_dns_record "$record_info"
+    else
+        echo "Error: Could not find DNS record for $subdomain.$1"
+    fi
+done
